### ISSUE TITLE
env file being declared twice in the docker-compose file

### ISSUE THREAD

**Issue by jt196** [jt196/vanilla-cookbook#228]
```yml
services:
  app:
    image: jt196/vanilla-cookbook:latest
    container_name: vanilla-cookbook
    ports:
      - '3000:3000'
    volumes:
      - ./db:/app/prisma/db
      - ./uploads:/app/uploads
      - ./.env:/app/.env
    env_file:
      - .env
```

This shouldn't be there: ` - ./.env:/app/.env`
